<?php

/**
 * Implements hook_form_alter().
 */
function field_help_helper_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $account = \Drupal::currentUser();
  if (!$account->hasPermission('edit field help text')) {
    return;
  }
  $form['#attached']['library'][] = 'field_help_helper/styles';
  $form_object = $form_state->getFormObject();
  $entity = is_a($form_object, 'Drupal\Core\Entity\EntityForm') ? $form_object->getEntity() : NULL;
  if (!empty($entity) && is_a($entity, 'Drupal\Core\Entity\FieldableEntityInterface')) {
    $entity_field_manager = \Drupal::service('entity_field.manager');

    $all_fields = $entity_field_manager->getFieldDefinitions($entity->getEntityTypeId(), $entity->bundle());
    $base_fields = $entity_field_manager->getBaseFieldDefinitions($entity->getEntityTypeId());

    foreach ($all_fields as $field_name => $field) {
      if (!array_key_exists($field_name, $base_fields)) {
        $form[$field_name]['field_help_helper'] = _field_help_helper_get_description_with_edit_link($field);
      }
    }
  }
}

/**
 * Retrieve the field help edit link build array.
 */
function _field_help_helper_get_description_with_edit_link(\Drupal\field\FieldConfigInterface $field_config) {
  $build = array();

  if (!empty($field_config)) {
    $build = [
      'field_help_helper_link' => [
        '#type' => 'link',
        '#title' => t('<i class="helper"></i><span>Edit help text</span>'),
        '#url' => \Drupal\Core\Url::fromRoute('field_help_helper.form_edit_field_help', ['field_id' => $field_config->id()], ['query' => ['destination' => \Drupal::service('path.current')->getPath()]]),
      ],
    ];
  }

  return $build;
}
