<?php

/**
 * Implements hook_form_alter().
 */
function field_help_helper_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $account = \Drupal::currentUser();
  if (!$account->hasPermission('edit field help text')) {
    return;
  }

  $form['#attached']['library'][] = 'field_help_helper/styles';
  $form_object = $form_state->getFormObject();
  $entity = ($form_object instanceof Drupal\Core\Entity\EntityForm) ? $form_object->getEntity() : NULL;
  if (!empty($entity) && ($entity instanceof Drupal\Core\Entity\FieldableEntityInterface)) {
    foreach (field_help_helper_get_fields($entity) as $field_name => $field) {
      $form[$field_name]['field_help_helper'] = _field_help_helper_get_description_with_edit_link($field);
    }
  }
}

/**
 * Get the configurable fields for a given entity.
 *
 * @param \Drupal\Core\Entity\FieldableEntityInterface $entity
 *   The fieldable entity object of the entity for which to retrieve the configurable fields.
 *
 * @return array
 *    Returns an array of configurable fields for the specified entity.
 */
function field_help_helper_get_fields(\Drupal\Core\Entity\FieldableEntityInterface $entity) {
  $entity_field_manager = \Drupal::service('entity_field.manager');

  $all_fields = $entity_field_manager->getFieldDefinitions($entity->getEntityTypeId(), $entity->bundle());
  $base_fields = $entity_field_manager->getBaseFieldDefinitions($entity->getEntityTypeId());

  return array_filter($all_fields, function($field) use ($base_fields) {
    return (!array_key_exists($field->getName(), $base_fields));
  });
}

/**
 * Retrieve the field help edit link build array.
 */
function _field_help_helper_get_description_with_edit_link(\Drupal\field\FieldConfigInterface $field_config) {
  $build = array();

  if (!empty($field_config)) {
    $build = [
      'field_help_helper_link' => [
        '#type' => 'link',
        '#title' => \Drupal\Core\Render\Markup::create('<i class="helper"></i><span>' . t('Edit help text') . '</span>'),
        '#url' => \Drupal\Core\Url::fromRoute('field_help_helper.form_edit_field_help', ['field_id' => $field_config->id()], ['attributes' => ['target' => '_blank']]),
      ],
    ];
  }

  return $build;
}
